parameters:
#    ace_board.example.class: Ace\BoardBundle\Example

services:
#    ace_board.example:
#        class: %ace_board.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
