parameters:
#    ace_board.example.class: Ace\BoardBundle\Example

services:
#    ace_board.example:
#        class: %ace_board.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    ace_board.defaultcontroller:
        class:        Ace\BoardBundle\Controller\DefaultController
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
            securitycontext: "@security.context"
            container: "@service_container"